// <auto-generated />
namespace Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class clientsandticketsadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(clientsandticketsadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201805221718292_clients-and-tickets-added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
